[package]
name = "mpeg_encoder"
version = "0.2.1"
authors = ["Sébastien Crozet <developer@crozet.re>"]

description = "A simple ffmpeg video encoder."
repository = "https://github.com/sebcrozet/mpeg_encoder"
readme = "README.md"
keywords = [ "encoder", "ffmpeg", "mpeg", "video" ]
license = "BSD-3-Clause"

[dependencies.ffmpeg-sys]
default-features = false
features = [ "avformat", "swscale" ]
git = "https://github.com/meh/rust-ffmpeg-sys"
rev = "ba724c36"